services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    labels:
      - "org.springframework.boot.service-connection=mongodb"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: